### ISSUE TITLE
Missing user @BaaaaaM

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cycamore-feedstock#7]
Appears the user @BaaaaaM is missing. They are [listed]( https://github.com/conda-forge/cycamore-feedstock/blob/6a0d2e1b574e6650da45072b4ea613e5459964fd/recipe/meta.yaml#L41 ) as a maintainer. Did they change their username or delete their account? This appears to be [blocking]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/194079954#L2433-L2441 ) the team update script. In either event, could we please have the maintainer list updated?

**Comment by bam241** [comment]
Yes I change my username yesterday to bam241
Sorry about it
Can I do something to fix that?

**Comment by bam241** [comment]
I PR a fix for that on all repo I am listed as maintainer.
@scopatz @gonuke could you take look ?
#8
conda-forge/cymetric-feedstock#4
conda-forge/cyclus-build-deps-feedstock#5
conda-forge/cyclus-feedstock#19

**Comment by jakirkham** [comment]
Thanks @bam241. That would be the way to fix it.

No need to do this now, but it is fine to add `[ci skip]` in the commit messages for these sorts of changes as they don't strictly need to run on CI as we aren't changing the build in any way. Just for future reference. 😉

**Comment by jakirkham** [comment]
Friendly nudge @scopatz. When you have a chance, could you please take a look at @bam241's PRs listed above? Thanks.

**Comment by scopatz** [comment]
Sorry about the delay. I was obsessed with cyclus/cyclus#1342

**Comment by jakirkham** [comment]
No worries. Thanks @scopatz.

Just trying to avoid the steady stream of `@` core mentions that often follow things like the team update script breaking. Maybe this is just more motivation to implement a better solution ( https://github.com/conda-forge/conda-forge-webservices/issues/63 ).

Also please don't forget PR ( https://github.com/conda-forge/cyclus-feedstock/pull/19 ).

**Comment by jakirkham** [comment]
Think we have resolved this FWICT. So am going to close it out. Thanks @bam241 and @scopatz for helping straighten this out.
